# ssp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-password
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp
  template:
    metadata:
      labels:
        app: ssp
    spec:
      containers:
      - name: ssp-container
        image: ltbproject/self-service-password:latest
        ports:
        - containerPort: 81
        volumeMounts:
        - name: ssp-config-volume
          mountPath: /var/www/conf/config.inc.local.php
          subPath: config.inc.local.php
      volumes:
      - name: ssp-config-volume
        configMap:
          name: ssp-config
          items:
          - key: "0" # The key in the ConfigMap's 'data' section
            path: config.inc.local.php # The name of the file created inside the volume (must match subPath)
